version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  matrix-tests:
    jobs:
      - node/test:
          version: 13.11.0
          filters:
            branches:
              only:
                - main
                - dev
      - node/test:
          version: 12.16.0
          filters:
            branches:
              only: main
      - node/test:
          version: 10.19.0
          filters:
            branches:
              only: main
